# Generated by Django 4.1.6 on 2023-02-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baham', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='picture1',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='picture2',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
